efi: 
    mountPoint: "/boot/efi"
    recommendedSize:    1G
    minimumSize:        0.5G
    label:              "EFI"
userSwapChoices:
    - none      # Create no swap, use no swap
    - small     # Up to 4GB
    - suspend   # At least main memory size
    # - reuse     # Re-use existing swap, but don't create any (unsupported right now)
    - file      # To swap file instead of partition

# Correctly draw nested (e.g. logical) partitions as such.
drawNestedPartitions:   false

# Show/hide partition labels on manual partitioning page.
alwaysShowPartitionLabels: true

lvm:
  enable: true
initialSwapChoice: none
defaultFileSystemType:  "xfs"
directoryFilesystemRestrictions:
    - mountpoint: "/boot/efi"
      allowedFilesystemTypes: ["fat32"]
      onlyWhenMountpoint: true
    - directory: "/boot"
      allowedFilesystemTypes: ["fat32"]
    - directory: "/"
      allowedFilesystemTypes: ["ext4","xfs","btrfs"]
partitionLayout:
    - name: "EFI"
      type: "c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
      filesystem: "fat32"
      noEncrypt: true
      mountPoint: "/boot/efi"
      minSize: 500M
      size: 1000M
      attributes: 0xffff000000000003
    - name: "XBOOTLDR"
      type: "bc13c2ff-59e6-4262-a352-b275fd6f7172"
      filesystem: "fat32"
      noEncrypt: true
      mountPoint: "/boot"
      minSize: 1000M
      attributes: 0xffff000000000003
    - name: "rootfs"
      type: "72ec70a6-cf74-40e6-bd49-4bda08e8f224"
      filesystem: "xfs"
      noEncrypt: true
      mountPoint: "/"
      minSize: 1000M
      size: 100%
      attributes: 0xffff000000000003

essentialMounts: [ "live-*", "control", "ventoy" ]
