dontChroot: true
verbose: true
timeout: 30000
script:
- command: "dnf -y --installroot=${ROOT} install dnf5 system-repos system-release ca-certificates ca-certificates-mozilla --nogpgcheck --use-host-config"
  verbose: true
- command: "mkdir -p ${ROOT}/usr/lib/kernel/install.d"
- command: "cp /etc/resolv.conf ${ROOT}/etc/resolv.conf"
- command: "cp /etc/yum.repos.d/* ${ROOT}/etc/yum.repos.d/"
- command: "mkdir ${ROOT}/etc/kernel/"
- command: "echo root=UUID=`grub-probe --target=fs_uuid ${ROOT}` audit=0 > ${ROOT}/etc/kernel/cmdline"
- command: "echo layout=bls > ${ROOT}/etc/kernel/install.conf"
- command: "mkdir ${ROOT}/etc/grub.d"
- command: "cp /etc/calamares/openruyi-scripts/28_blsuki  ${ROOT}/etc/grub.d"

