showSupportUrl: true
showDonateUrl: https://openruyi.cn
requirements:
   requiredStorage: 5.5
   check:
      - storage
      - ram
      - screen
   required:
      - ram
geoip:
    style:    "none"
    url:      "https://geoip.kde.org/v1/ubiquity"  # extended XML format
    selector: "CountryCode"  # blank uses default, which is wrong
